apiVersion: v1
kind: Pod
metadata:
  name: vault-client
  labels:
    app: vault-client
spec:
  serviceAccountName: vault-sa
  containers:
  - name: vault-client
    image: alpine
    command: ["/bin/sh", "-c", "apk add --no-cache curl jq && sleep 3600"]
